"""empty message

Revision ID: 44e5df2eb8a2
Revises: 
Create Date: 2020-02-03 22:46:39.800839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e5df2eb8a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('probability', sa.String(length=60), nullable=True),
    sa.Column('precipitation', sa.String(length=60), nullable=True),
    sa.Column('minimum', sa.String(length=60), nullable=True),
    sa.Column('maximum', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
