"""empty message

Revision ID: daa7aa9cb694
Revises: 
Create Date: 2020-02-06 13:25:10.535433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa7aa9cb694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('probability', sa.String(length=60), nullable=True),
    sa.Column('precipitation', sa.String(length=60), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('min_', sa.String(length=60), nullable=True),
    sa.Column('max_', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    # ### end Alembic commands ###
